(define (cube x) (* x x x))

(define (simpson-rule f a b n)
  (if (odd? n)
      (error "n must be even")
      (let ((h (/ (- b a) n)))
        (define (x-k k)
          (+ a (* k h)))
        (define (sum-odds k sum)
          (if (= k (- n 1))
              (+ sum (f (x-k k)))
              (sum-odds (+ k 2) (+ sum (f (x-k k))))))
        (define (sum-evens k sum)
          (if (= k (- n 2))
              (+ sum (f (x-k k)))
              (sum-evens (+ k 2) (+ sum (f (x-k k))))))
        (* (/ h 3) (+ (f a) 
                      (* 4 (sum-odds 1 0)) 
                      (* 2 (sum-evens 2 0)) 
                      (f b))))))

;; Example usage
(define result (simpson-rule cube 0 1 1000))
(display result)
(newline)
